HABIT_TEMPLATES = [
    {
        'id': 'meditation',
        'name': 'Daily Meditation',
        'description': 'Practice mindfulness for 10 minutes each day to reduce stress and improve focus.',
        'icon': 'moon',
        'theme_color': '#8b5cf6',
        'visual_model_type': 'graph',
        'settings': {
            'graph_type': 'line',
            'time_range': 30,
        },
        'tags': ['mindfulness', 'mental health', 'wellness'],
    },
    {
        'id': 'exercise',
        'name': 'Daily Exercise',
        'description': 'Get at least 30 minutes of physical activity every day.',
        'icon': 'bicycle',
        'theme_color': '#ef4444',
        'visual_model_type': 'graph',
        'settings': {
            'graph_type': 'line',
            'time_range': 30,
        },
        'tags': ['fitness', 'health', 'exercise'],
    },
    {
        'id': 'reading',
        'name': 'Read 30 Minutes',
        'description': 'Spend 30 minutes reading a book each day.',
        'icon': 'book',
        'theme_color': '#0ea5e9',
        'visual_model_type': 'graph',
        'settings': {
            'graph_type': 'line',
            'time_range': 30,
        },
        'tags': ['learning', 'reading', 'self-improvement'],
    },
    {
        'id': 'water',
        'name': 'Drink 8 Glasses of Water',
        'description': 'Stay hydrated by drinking at least 8 glasses of water daily.',
        'icon': 'droplet',
        'theme_color': '#06b6d4',
        'visual_model_type': 'percentage',
        'settings': {
            'min_value': 0,
            'max_value': 8,
            'current_value': 0,
            'unit': 'glasses',
        },
        'tags': ['health', 'hydration', 'wellness'],
    },
    {
        'id': 'sleep',
        'name': 'Sleep 8 Hours',
        'description': 'Get a full 8 hours of sleep each night.',
        'icon': 'moon',
        'theme_color': '#6366f1',
        'visual_model_type': 'graph',
        'settings': {
            'graph_type': 'line',
            'time_range': 30,
        },
        'tags': ['health', 'sleep', 'wellness'],
    },
    {
        'id': 'journal',
        'name': 'Daily Journaling',
        'description': 'Write in your journal for 10 minutes each day to reflect and process.',
        'icon': 'pen',
        'theme_color': '#f59e0b',
        'visual_model_type': 'graph',
        'settings': {
            'graph_type': 'line',
            'time_range': 30,
        },
        'tags': ['mindfulness', 'writing', 'self-improvement'],
    },
    {
        'id': 'no_social_media',
        'name': 'No Social Media',
        'description': 'Avoid social media for the entire day.',
        'icon': 'phone',
        'theme_color': '#10b981',
        'visual_model_type': 'graph',
        'settings': {
            'graph_type': 'line',
            'time_range': 30,
        },
        'tags': ['digital detox', 'productivity', 'focus'],
    },
    {
        'id': 'cook_meal',
        'name': 'Cook a Healthy Meal',
        'description': 'Prepare a home-cooked healthy meal instead of eating out.',
        'icon': 'egg',
        'theme_color': '#22c55e',
        'visual_model_type': 'graph',
        'settings': {
            'graph_type': 'line',
            'time_range': 30,
        },
        'tags': ['health', 'cooking', 'nutrition'],
    },
    {
        'id': 'learning',
        'name': 'Learn Something New',
        'description': 'Spend 20 minutes learning a new skill or topic.',
        'icon': 'laptop',
        'theme_color': '#a855f7',
        'visual_model_type': 'graph',
        'settings': {
            'graph_type': 'line',
            'time_range': 30,
        },
        'tags': ['learning', 'education', 'self-improvement'],
    },
    {
        'id': 'music_practice',
        'name': 'Practice Instrument',
        'description': 'Spend 30 minutes practicing a musical instrument.',
        'icon': 'music-note',
        'theme_color': '#ec4899',
        'visual_model_type': 'graph',
        'settings': {
            'graph_type': 'line',
            'time_range': 30,
        },
        'tags': ['music', 'practice', 'creativity'],
    },
    {
        'id': 'morning_routine',
        'name': 'Morning Routine',
        'description': 'Complete your full morning routine every day.',
        'icon': 'sunrise',
        'theme_color': '#f97316',
        'visual_model_type': 'calendar',
        'settings': {
            'schedule': ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
            'reminder_time': '07:00',
            'activity_types': [],
            'times_per_day': 1,
        },
        'tags': ['routine', 'productivity', 'morning'],
    },
    {
        'id': 'gym',
        'name': 'Gym Session',
        'description': 'Hit the gym for a workout session.',
        'icon': 'controller',
        'theme_color': '#ef4444',
        'visual_model_type': 'calendar',
        'settings': {
            'schedule': ['monday', 'wednesday', 'friday'],
            'reminder_time': '17:00',
            'activity_types': [],
            'times_per_day': 1,
        },
        'tags': ['fitness', 'gym', 'exercise'],
    },
]
